### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rebaz36**
# This Project Consisted of the Following Tasks

### Add
- add necessary dependencies
- add redux config
- add core components
- add crypto slice
- add crypto detail slice
- add Styles for Home Page
- add Styles for Details Page
- add Styles for NavBar
- add Back Button
- add props validation
- add gh-pages dependency for deployment
- add Test Cases

### Implement 
- set up dependencies
- implementation of the Project stature
- configure react-router
- Redux Configuration
- fetch data from the redux store
- display data in the home and details page
- Deploy to gh-Pages

### Delete
- clear unnecessary files
- clear unnecessary codes

# References
## Live Demo

[Live Demo](https://rebaz36.github.io/React-Capstone/)

## Loom Video Presentation

[Video Pesentation](https://www.loom.com/share/6ec49865b5634a4fa8e74c5d75fb49c9)

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @rebaz36, Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this is a requirement to get a review

**Comment by prolajumokeoni** [comment]
Hi @, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the updated readme template, 
Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme,

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by AmaduKamara — CHANGES_REQUESTED** [review]
# Status: Required Changes ♻️♻️♻️ 

Hi @rebaz36,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly
✅ Linter checks passed
✅ Used Redux well 👍
✅ Code is professional and well structured 👍 
✅ Good commit messages 👍 
✅ Good descriptive PR 👍 

## Required Changes ♻️
_Check the comments under the review._
You did great on your project so far, your code is well-structured and professional. Hence, it would be great to make a few changes in a few areas to help make your project stand out to potential employers should they bump into your repo 👍 

- [ ] Kindly re-do the video presentation. The background is a bit distracting and the sound playback is fast. Kindly take note of the following in order to help you record a better video presentation for your app:
-> Do the recording in a quiet place with no sound and no distractions in the background
-> First, introduce yourself, and the project objectives (This is my React capstone at Microverse in which we were asked to use an API and build a web-based mobile app that displays matric data about a topic of our interest and I choose this blablabla API), then the features the app has and then go straight to the demo of the app.
-> After the quick demo display, you then show just one part of your code that you are proud of implementing. Explain briefly what that code does in the app.
-> And I believe you would want to smile and thank the person for their time in watching your presentation. 👍

- [ ] All the presentations should be within 5 minutes max

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] You could add a placeholder text on the input field so users of the app know that can search for something. Currently, as it is, the (Filter:) word is not enough for everyone to know they can search, but the placeholder will help make them know there is an input field for searching. It'll help for a better user experience of your app 👍 

image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by rebaz36** [comment]
Thanks @AmaduKamara Appreciate the Concise and detailed Review

**Comment by AmaduKamara** [comment]
You're welcome brother.
Keep doing great 👍

**Review by andersonlebon — APPROVED** [review]
### Hello @rebaz36 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------

**Comment by rebaz36** [comment]
Thanks @andersonlebon

**Pull request merged**
